/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uni.trier.zimk.sp.timetable.dual;

import de.uni.trier.zimk.sp.timetable.*;

/**
 *
 * @author Landry Ngani
 */
public class DualShiftViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form DayHoursViewPanel
     */
    public DualShiftViewPanel(DayShiftTimetableTableModel tableModel) {
        this.tableModel = tableModel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centralScrollPane = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        timeTable.setModel(getTableModel());
        timeTable.setRowHeight(70);
        centralScrollPane.setViewportView(timeTable);
        for(int i = 0; i<getTableModel().getColumnCount(); i++ ){
            timeTable.getColumnModel().getColumn(i).setCellRenderer( new ShiftCellRenderer() );
        }

        add(centralScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane centralScrollPane;
    private javax.swing.JTable timeTable;
    // End of variables declaration//GEN-END:variables

    private DayShiftTimetableTableModel tableModel;

    public DayShiftTimetableTableModel getTableModel() {
        return tableModel;
    }

    public void setTableModel(DayShiftTimetableTableModel tableModel) {
        this.tableModel = tableModel;
        timeTable.setModel(tableModel);
    }

}
