/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uni.trier.zimk.sp.timetable.location;

import de.uni.trier.zimk.sp.timetable.preferences.*;
import de.uni.trier.zimk.sp.timetable.oo.*;
import de.uni.trier.zimk.sp.timetable.util.Timetable;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Landry Ngani
 */
public class LocationAwareTimetableView extends javax.swing.JPanel {


    public LocationAwareTimetableView( Timetable timetable, LocationAwareTableModel configurationTableModel) {
        this.timetable = timetable;
        this.configurationTableModel =  configurationTableModel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workerTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        workerTable.setModel(configurationTableModel);
        workerTable.setRowHeight(60);
        workerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workerTable);
        for(int i = 0; i<configurationTableModel.getColumnCount(); i++ ){
            workerTable.getColumnModel().getColumn(i).setCellRenderer(
                new de.uni.trier.zimk.sp.timetable.location.LocationShiftWorkerCellRenderer(timetable) );
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void workerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerTableMouseClicked
        if( evt.isControlDown() ){
            
            Point p = evt.getPoint();
            int row = workerTable.rowAtPoint(p); 
            int column = workerTable.columnAtPoint(p); 
            
            LocationAwareTableModel tableModel = (LocationAwareTableModel) ((JTable)evt.getComponent()).getModel();
            LocationShift shift = (LocationShift)tableModel.getValueAt(row, column);
            
            if( shift != null ){
                
                //List<Worker> volunteers = new WorkerDialog( timetable, shift).getSelectedWorkers();
                //Collections.sort(volunteers, new WorkerComparable());
                try {
                    int capacity = Integer.parseInt( 
                            JOptionPane.showInputDialog(this, "Enter the shift's capacity please :" , "Timetable.", JOptionPane.QUESTION_MESSAGE) 
                            );
                    shift.setCapacity( capacity );
                }
                catch(NumberFormatException e){
                    e.printStackTrace( System.out );
                }
                
                timetable.fireStateChanged();
                
            }
        }
    }//GEN-LAST:event_workerTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workerTable;
    // End of variables declaration//GEN-END:variables


    private Timetable timetable;
    private  LocationAwareTableModel configurationTableModel;
    
    
    public void setTableModel( LocationAwareTableModel configurationTableModel) {
        this.configurationTableModel = configurationTableModel;
        workerTable.setModel(configurationTableModel);
    }

    public LocationAwareTableModel getLocationAwareTableModel() {
        return configurationTableModel;
    }

      /**
     * 
     * @param state 
     */
    public void stateToDisplay(TimetableState state){
       
        for(Location loc : state.getLocations()){
            if(loc.equals(configurationTableModel.getValueList())){
                configurationTableModel.setValueList(loc);
                break;
            }
        }
        
        this.repaint();
    }
    
    
}
