/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uni.trier.zimk.sp.timetable.configuration;

import de.uni.trier.zimk.sp.timetable.preferences.*;
import de.uni.trier.zimk.sp.timetable.ShiftPreferencesCellRenderer;
import de.uni.trier.zimk.sp.timetable.oo.LocationShift;
import de.uni.trier.zimk.sp.timetable.preferences.UsersAndPreferencesModel;
import de.uni.trier.zimk.sp.timetable.preferences.EditableDayShiftTimetableTableModel;
import de.uni.trier.zimk.sp.timetable.oo.Shift;
import de.uni.trier.zimk.sp.timetable.oo.Worker;
import de.uni.trier.zimk.sp.timetable.oo.WorkerComparable;
import de.uni.trier.zimk.sp.timetable.util.Timetable;
import java.awt.Point;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Landry Ngani
 */
public class ConfigurationEditorView extends javax.swing.JPanel {

    /**
     * Creates new form UsersAndPreferencesEditor
     * /
    public UsersAndPreferencesEditor() {
        initComponents();
    }
    */
    

    public ConfigurationEditorView( Timetable timetable, ConfigurationTableModel configurationTableModel) {
        this.timetable = timetable;
        this.configurationTableModel =  configurationTableModel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workerTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        workerTable.setModel(configurationTableModel);
        workerTable.setRowHeight(100);
        workerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workerTable);
        for(int i = 0; i<configurationTableModel.getColumnCount(); i++ ){
            workerTable.getColumnModel().getColumn(i).setCellRenderer(
                new LocationShiftCellRenderer(timetable) );
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void workerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerTableMouseClicked
        if( evt.isControlDown() ){
            
            Point p = evt.getPoint();
            int row = workerTable.rowAtPoint(p); 
            int column = workerTable.columnAtPoint(p); 
            
            ConfigurationTableModel tableModel = (ConfigurationTableModel) ((JTable)evt.getComponent()).getModel();
            LocationShift shift = (LocationShift)tableModel.getValueAt(row, column);
            
            if( shift != null ){
                
                //List<Worker> volunteers = new WorkerDialog( timetable, shift).getSelectedWorkers();
                //Collections.sort(volunteers, new WorkerComparable());
                try {
                    int capacity = Integer.parseInt( 
                            JOptionPane.showInputDialog(this, "Enter the shift's capacity please :" , "Timetable.", JOptionPane.QUESTION_MESSAGE) 
                            );
                    shift.setCapacity( capacity );
                }
                catch(NumberFormatException e){
                    e.printStackTrace( System.out );
                }
                
                timetable.fireStateChanged();
                
            }
        }
    }//GEN-LAST:event_workerTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workerTable;
    // End of variables declaration//GEN-END:variables


    private Timetable timetable;
    private  ConfigurationTableModel configurationTableModel;
    
    
    public void setTableModel( ConfigurationTableModel configurationTableModel) {
        this.configurationTableModel = configurationTableModel;
        workerTable.setModel(configurationTableModel);
    }
}
