/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uni.trier.zimk.sp.timetable;

/**
 *
 * @author Landry Ngani
 */
public class DayHoursViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form DayHoursViewPanel
     */
    public DayHoursViewPanel(DayShiftTimetableTableModel tableModel) {
        this.tableModel = tableModel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centralScrollPane = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        timeTable.setModel(getTableModel());
        timeTable.setRowHeight(100);
        centralScrollPane.setViewportView(timeTable);
        for(int i = 0; i<getTableModel().getColumnCount(); i++ ){
            timeTable.getColumnModel().getColumn(i).setCellRenderer( new ShiftCellRenderer() );
        }

        add(centralScrollPane, java.awt.BorderLayout.CENTER);

        statusPanel.setLayout(new java.awt.BorderLayout(10, 10));

        statusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modified_icon.png"))); // NOI18N
        statusLabel.setText("  ");
        statusPanel.add(statusLabel, java.awt.BorderLayout.CENTER);

        add(statusPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane centralScrollPane;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTable timeTable;
    // End of variables declaration//GEN-END:variables

    private DayShiftTimetableTableModel tableModel;

    public DayShiftTimetableTableModel getTableModel() {
        return tableModel;
    }

    public void setTableModel(DayShiftTimetableTableModel tableModel) {
        this.tableModel = tableModel;
        timeTable.setModel(tableModel);
    }

}
